version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: postgres_container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: respire_bem
    ports:
      - '5432:5432'
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  mongo:
    image: mongo:7
    container_name: mongo_container
    ports:
      - '27017:27017'
    volumes:
      - ./data/mongo:/data/db
