name: CI/CD Pipeline

on:
  pull_request:
    branches:
      - '*'
    types: [opened, synchronize]
  push:
    branches:
      - main

jobs:
  validation:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - uses: actions/checkout@v3
      - name: Run Validation
        run: |
          echo "Running Validation..."
          github-action run validate.yml
        shell: bash

  deploy:
    runs-on: ubuntu-latest
    needs: validation
    if: github.event_name == 'pull_request' || (github.event_name == 'push' && github.ref == 'refs/heads/main')
    steps:
      - uses: actions/checkout@v3
      - name: Run Deploy
        run: |
          echo "Running Deploy..."
          github-action run deploy.yml
        shell: bash
