name: Validation

on:
  pull_request:

jobs:
  validation:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set git to use CRLF
        run: |
          git config --global core.autocrlf true
          git config --global core.eol crlf
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.11.0'        
      - name: Install dependencies
        run: npm install      
      - name: Run lint
        run: npm run lint
      - name: Run format check
        run: npm run format
